<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductsSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            [
                'title' => 'Volkswagen Golf GTI 2020',
                'content' => 'Golf GTI en excelente estado, 30.000km, mantenimiento al día.',
                'price' => 25000,
                'estado_id' => 2,
                'category_id' => 1,
                'user_id' => 1,
                'toSend' => false,
                'isDeleted' => false,
                'isBoost' => true,
                'dimensionX' => 450,
                'dimensionY' => 180,
                'marca' => 'Volkswagen',
                'color' => 'Negro',
            ],
            [
                'title' => 'iPhone 14 Pro Max',
                'content' => 'Nuevo, precintado, 256GB de almacenamiento.',
                'price' => 1099,
                'estado_id' => 1,
                'category_id' => 2,
                'user_id' => 2,
                'toSend' => true,
                'isDeleted' => false,
                'isBoost' => true,
                'dimensionX' => 15,
                'dimensionY' => 7,
                'marca' => 'Apple',
                'color' => 'Gris Espacial',
            ],
            [
                'title' => 'Apartamento en el centro',
                'content' => '2 habitaciones, reformado, muy luminoso.',
                'price' => 180000,
                'estado_id' => 2,
                'category_id' => 3,
                'user_id' => 3,
                'toSend' => false,
                'isDeleted' => false,
                'isBoost' => true,
                'dimensionX' => 75,
                'dimensionY' => 65,
                'marca' => 'N/A',
                'color' => 'N/A',
            ],
            [
                'title' => 'Sofá moderno 3 plazas',
                'content' => 'Tapizado en tela, muy cómodo y como nuevo.',
                'price' => 450,
                'estado_id' => 2,
                'category_id' => 4,
                'user_id' => 1,
                'toSend' => true,
                'isDeleted' => false,
                'isBoost' => false,
                'dimensionX' => 220,
                'dimensionY' => 85,
                'marca' => 'IKEA',
                'color' => 'Gris',
            ],
            [
                'title' => 'Servicios de Jardinería',
                'content' => 'Mantenimiento de jardines y poda de árboles.',
                'price' => 25,
                'estado_id' => 1,
                'category_id' => 5,
                'user_id' => 2,
                'toSend' => false,
                'isDeleted' => false,
                'isBoost' => false,
                'dimensionX' => 0,
                'dimensionY' => 0,
                'marca' => 'N/A',
                'color' => 'N/A',
            ],
            [
                'title' => 'Bicicleta eléctrica Specialized',
                'content' => 'Motor Brose, batería 500Wh, poco uso.',
                'price' => 2800,
                'estado_id' => 2,
                'category_id' => 7,
                'user_id' => 3,
                'toSend' => true,
                'isDeleted' => false,
                'isBoost' => true,
                'dimensionX' => 180,
                'dimensionY' => 110,
                'marca' => 'Specialized',
                'color' => 'Rojo',
            ],
            [
                'title' => 'Portátil Gaming MSI',
                'content' => 'RTX 3070, 32GB RAM, i7 11th gen.',
                'price' => 1200,
                'estado_id' => 3,
                'category_id' => 2,
                'user_id' => 1,
                'toSend' => true,
                'isDeleted' => false,
                'isBoost' => false,
                'dimensionX' => 35,
                'dimensionY' => 25,
                'marca' => 'MSI',
                'color' => 'Negro',
            ],
            [
                'title' => 'Clases particulares matemáticas',
                'content' => 'Profesor con 10 años de experiencia.',
                'price' => 20,
                'estado_id' => 1,
                'category_id' => 5,
                'user_id' => 2,
                'toSend' => false,
                'isDeleted' => false,
                'isBoost' => false,
                'dimensionX' => 0,
                'dimensionY' => 0,
                'marca' => 'N/A',
                'color' => 'N/A',
            ],
            [
                'title' => 'Mesa de comedor vintage',
                'content' => 'Madera maciza, extensible, 6-8 personas.',
                'price' => 350,
                'estado_id' => 3,
                'category_id' => 4,
                'user_id' => 3,
                'toSend' => true,
                'isDeleted' => false,
                'isBoost' => false,
                'dimensionX' => 160,
                'dimensionY' => 90,
                'marca' => 'Vintage',
                'color' => 'Marrón',
            ],
            [
                'title' => 'Seat León FR 2019',
                'content' => '150cv, gasolina, techo panorámico.',
                'price' => 19500,
                'estado_id' => 2,
                'category_id' => 1,
                'user_id' => 1,
                'toSend' => false,
                'isDeleted' => false,
                'isBoost' => true,
                'dimensionX' => 430,
                'dimensionY' => 180,
                'marca' => 'Seat',
                'color' => 'Azul',
            ],
            [
                'title' => 'Set de pesas y mancuernas',
                'content' => 'Juego completo de 50kg ajustables.',
                'price' => 180,
                'estado_id' => 2,
                'category_id' => 7,
                'user_id' => 2,
                'toSend' => true,
                'isDeleted' => false,
                'isBoost' => false,
                'dimensionX' => 40,
                'dimensionY' => 30,
                'marca' => 'Decathlon',
                'color' => 'Negro',
            ],
            [
                'title' => 'Local comercial céntrico',
                'content' => '80m2, escaparate amplio, recién reformado.',
                'price' => 150000,
                'estado_id' => 2,
                'category_id' => 3,
                'user_id' => 3,
                'toSend' => false,
                'isDeleted' => false,
                'isBoost' => true,
                'dimensionX' => 80,
                'dimensionY' => 80,
                'marca' => 'N/A',
                'color' => 'N/A',
            ],
            [
                'title' => 'Lavadora Samsung EcoBubble',
                'content' => '9kg, 1400rpm, eficiencia A+++.',
                'price' => 380,
                'estado_id' => 3,
                'category_id' => 4,
                'user_id' => 1,
                'toSend' => true,
                'isDeleted' => false,
                'isBoost' => false,
                'dimensionX' => 60,
                'dimensionY' => 85,
                'marca' => 'Samsung',
                'color' => 'Blanco',
            ],
            [
                'title' => 'Monitor Gaming 32" Curvo',
                'content' => '165Hz, 1ms, QHD, FreeSync Premium.',
                'price' => 299,
                'estado_id' => 1,
                'category_id' => 2,
                'user_id' => 2,
                'toSend' => true,
                'isDeleted' => false,
                'isBoost' => false,
                'dimensionX' => 70,
                'dimensionY' => 45,
                'marca' => 'AOC',
                'color' => 'Negro',
            ],
            [
                'title' => 'Servicios de fotografía',
                'content' => 'Bodas, eventos, books profesionales.',
                'price' => 200,
                'estado_id' => 1,
                'category_id' => 5,
                'user_id' => 3,
                'toSend' => false,
                'isDeleted' => false,
                'isBoost' => true,
                'dimensionX' => 0,
                'dimensionY' => 0,
                'marca' => 'N/A',
                'color' => 'N/A',
            ],
            [
                'title' => 'Cinta de correr profesional',
                'content' => 'Motor 3.5HP, programas automáticos.',
                'price' => 750,
                'estado_id' => 2,
                'category_id' => 7,
                'user_id' => 1,
                'toSend' => true,
                'isDeleted' => false,
                'isBoost' => false,
                'dimensionX' => 180,
                'dimensionY' => 85,
                'marca' => 'NordicTrack',
                'color' => 'Negro',
            ],
            [
                'title' => 'Honda CBR 600RR',
                'content' => '2018, 15.000km, extras incluidos.',
                'price' => 8500,
                'estado_id' => 3,
                'category_id' => 1,
                'user_id' => 2,
                'toSend' => false,
                'isDeleted' => false,
                'isBoost' => true,
                'dimensionX' => 210,
                'dimensionY' => 110,
                'marca' => 'Honda',
                'color' => 'Rojo/Negro',
            ],
            [
                'title' => 'iPad Pro 12.9 2022',
                'content' => 'M2, 256GB, WiFi + Cellular.',
                'price' => 950,
                'estado_id' => 2,
                'category_id' => 2,
                'user_id' => 3,
                'toSend' => true,
                'isDeleted' => false,
                'isBoost' => false,
                'dimensionX' => 28,
                'dimensionY' => 21,
                'marca' => 'Apple',
                'color' => 'Plata',
            ],
            [
                'title' => 'Piso ático con terraza',
                'content' => '3 habitaciones, terraza 40m2, parking.',
                'price' => 295000,
                'estado_id' => 2,
                'category_id' => 3,
                'user_id' => 1,
                'toSend' => false,
                'isDeleted' => false,
                'isBoost' => true,
                'dimensionX' => 100,
                'dimensionY' => 90,
                'marca' => 'N/A',
                'color' => 'N/A',
            ],
            [
                'title' => 'Nevera americana Samsung',
                'content' => 'Dispensador agua/hielo, panel digital.',
                'price' => 850,
                'estado_id' => 3,
                'category_id' => 4,
                'user_id' => 2,
                'toSend' => true,
                'isDeleted' => false,
                'isBoost' => false,
                'dimensionX' => 90,
                'dimensionY' => 178,
                'marca' => 'Samsung',
                'color' => 'Inox',
            ],
            [
                'title' => 'Profesor nativo de inglés',
                'content' => 'Clases online o presenciales.',
                'price' => 25,
                'estado_id' => 1,
                'category_id' => 5,
                'user_id' => 3,
                'toSend' => false,
                'isDeleted' => false,
                'isBoost' => false,
                'dimensionX' => 0,
                'dimensionY' => 0,
                'marca' => 'N/A',
                'color' => 'N/A',
            ],
            [
                'title' => 'Raqueta Wilson Pro Staff',
                'content' => 'Modelo RF97, poco uso.',
                'price' => 180,
                'estado_id' => 2,
                'category_id' => 7,
                'user_id' => 1,
                'toSend' => true,
                'isDeleted' => false,
                'isBoost' => false,
                'dimensionX' => 70,
                'dimensionY' => 30,
                'marca' => 'Wilson',
                'color' => 'Negro',
            ],
            [
                'title' => 'Diseñador gráfico freelance',
                'content' => 'Logos, branding, web design.',
                'price' => 35,
                'estado_id' => 1,
                'category_id' => 6,
                'user_id' => 2,
                'toSend' => false,
                'isDeleted' => false,
                'isBoost' => true,
                'dimensionX' => 0,
                'dimensionY' => 0,
                'marca' => 'N/A',
                'color' => 'N/A',
            ],
            [
                'title' => 'Consola PS5 Digital',
                'content' => 'Nueva, sin estrenar, 2 mandos.',
                'price' => 450,
                'estado_id' => 1,
                'category_id' => 2,
                'user_id' => 3,
                'toSend' => true,
                'isDeleted' => false,
                'isBoost' => true,
                'dimensionX' => 40,
                'dimensionY' => 25,
                'marca' => 'Sony',
                'color' => 'Blanco',
            ],
            [
                'title' => 'Programador Full Stack',
                'content' => 'Desarrollo web y aplicaciones móviles.',
                'price' => 45,
                'estado_id' => 1,
                'category_id' => 6,
                'user_id' => 1,
                'toSend' => false,
                'isDeleted' => false,
                'isBoost' => true,
                'dimensionX' => 0,
                'dimensionY' => 0,
                'marca' => 'N/A',
                'color' => 'N/A',
            ],
            [
                'title' => 'Mesa de ping pong profesional',
                'content' => 'Plegable, incluye red y raquetas.',
                'price' => 295,
                'estado_id' => 2,
                'category_id' => 7,
                'user_id' => 2,
                'toSend' => true,
                'isDeleted' => false,
                'isBoost' => false,
                'dimensionX' => 274,
                'dimensionY' => 152,
                'marca' => 'Cornilleau',
                'color' => 'Azul',
            ]
        ];

        foreach ($products as $productData) {
            $product = new Product();
            $product->title = $productData['title'];
            $product->content = $productData['content'];
            $product->price = $productData['price'];
            $product->estado_id = $productData['estado_id'];
            $product->category_id = $productData['category_id'];
            $product->user_id = $productData['user_id'];
            $product->toSend = $productData['toSend'];
            $product->isDeleted = $productData['isDeleted'];
            $product->isBoost = $productData['isBoost'];
            $product->dimensionX = $productData['dimensionX'];
            $product->dimensionY = $productData['dimensionY'];
            $product->marca = $productData['marca'];
            $product->color = $productData['color'];
            $product->save();
        }
    }
}