<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\ShippingAddress;

class ShippingAddressSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $ship_add = [
            [
                'address' => 'Calle Ficticia 123',
                'zip' => '28001',
                'country' => 'Chamartín',
                'city' => 'Madrid',
                'role_address' => '1',
                'notes' => 'Horario de atención: Lunes a Viernes de 9:00 a 18:00',
                'contact_name' => 'Centro Logístico Norte',
                'contact_phone' => '912345678',
                'contact_email' => 'norte@paqueteria.com',
            ],
            [
                'address' => 'Avenida Envíos 45',
                'zip' => '41012',
                'country' => 'Bellavista',
                'city' => 'Sevilla',
                'role_address' => '1',
                'notes' => 'Horario de atención: Lunes a Viernes de 9:00 a 18:00',
                'contact_name' => 'Estación Sur Paquetería',
                'contact_phone' => '955123456',
                'contact_email' => 'sur@paqueteria.com',
            ],
            [
                'address' => 'Plaza Mayor 1',
                'zip' => '08002',
                'country' => 'Ciutat Vella',
                'city' => 'Barcelona',
                'role_address' => '1',
                'notes' => 'Horario de atención: Lunes a Viernes de 9:00 a 18:00',
                'contact_name' => 'Punto Centro Recogida',
                'contact_phone' => '931234567',
                'contact_email' => 'centro@paqueteria.com',
            ],
            [
                'address' => 'Calle Valencia 85',
                'zip' => '46007',
                'country' => 'Ruzafa',
                'city' => 'Valencia',
                'role_address' => '1',
                'notes' => 'Horario de atención: Lunes a Viernes de 9:00 a 18:00',
                'contact_name' => 'Logística Este',
                'contact_phone' => '961112233',
                'contact_email' => 'este@paq.com',
            ],
            [
                'address' => 'Gran Vía 55',
                'zip' => '48011',
                'country' => 'Abando',
                'city' => 'Bilbao',
                'role_address' => '1',
                'notes' => 'Horario de atención: Lunes a Viernes de 9:00 a 18:00',
                'contact_name' => 'Punto Norte Bilbao',
                'contact_phone' => '944556677',
                'contact_email' => 'bilbao@paq.com',
            ],
            [
                'address' => 'Av. Andalucía 10',
                'zip' => '29007',
                'country' => 'Cruz de Humilladero',
                'city' => 'Málaga',
                'role_address' => '1',
                'notes' => 'Horario de atención: Lunes a Viernes de 9:00 a 18:00',
                'contact_name' => 'Paq Málaga',
                'contact_phone' => '952001122',
                'contact_email' => 'malaga@paq.com',
            ],
            [
                'address' => 'Calle Alfonso I 78',
                'zip' => '50003',
                'country' => 'Casco Antiguo',
                'city' => 'Zaragoza',
                'role_address' => '1',
                'notes' => 'Horario de atención: Lunes a Viernes de 9:00 a 18:00',
                'contact_name' => 'Centro Logístico Zaragoza',
                'contact_phone' => '976445566',
                'contact_email' => 'zaragoza@paq.com',
            ],
            [
                'address' => 'Calle Real 12',
                'zip' => '15003',
                'country' => 'city Vieja',
                'city' => 'A Coruña',
                'role_address' => '1',
                'notes' => 'Horario de atención: Lunes a Viernes de 9:00 a 18:00',
                'contact_name' => 'Punto Recogida Coruña',
                'contact_phone' => '981223344',
                'contact_email' => 'coruna@paq.com',
            ],
            [
                'address' => 'Calle Recogidas 9',
                'zip' => '18005',
                'country' => 'Ronda',
                'city' => 'Granada',
                'role_address' => '1',
                'notes' => 'Horario de atención: Lunes a Viernes de 9:00 a 18:00',
                'contact_name' => 'Establecimiento Granada Sur',
                'contact_phone' => '958778899',
                'contact_email' => 'granada@paq.com',
            ],
            [
                'address' => 'Gran Vía Escultor Salzillo 4',
                'zip' => '30004',
                'country' => 'Centro',
                'city' => 'Murcia',
                'role_address' => '1',
                'notes' => 'Horario de atención: Lunes a Viernes de 9:00 a 18:00',
                'contact_name' => 'Paq Murcia Central',
                'contact_phone' => '968332211',
                'contact_email' => 'murcia@paq.com',
            ],
            [
                'address' => 'Rúa do Príncipe 20',
                'zip' => '36202',
                'country' => 'Casco Vello',
                'city' => 'Vigo',
                'role_address' => '1',
                'notes' => 'Horario de atención: Lunes a Viernes de 9:00 a 18:00',
                'contact_name' => 'Centro Vigo Envíos',
                'contact_phone' => '986112233',
                'contact_email' => 'vigo@paq.com',
            ],
            [
                'address' => 'Avenida Ordoño II 17',
                'zip' => '24001',
                'country' => 'Centro',
                'city' => 'León',
                'role_address' => '1',
                'notes' => 'Horario de atención: Lunes a Viernes de 9:00 a 18:00',
                'contact_name' => 'Punto León Express',
                'contact_phone' => '987334455',
                'contact_email' => 'leon@paq.com',
            ],
            [
                'address' => 'Boulevard 5',
                'zip' => '20003',
                'country' => 'Parte Vieja',
                'city' => 'San Sebastián',
                'role_address' => '1',
                'notes' => 'Horario de atención: Lunes a Viernes de 9:00 a 18:00',
                'contact_name' => 'Recogidas Donostia',
                'contact_phone' => '943778899',
                'contact_email' => 'donosti@paq.com',
            ],
            [
                'address' => 'Plaza San Juan de Dios',
                'zip' => '11005',
                'country' => 'Centro Histórico',
                'city' => 'Cádiz',
                'role_address' => '1',
                'notes' => 'Horario de atención: Lunes a Viernes de 9:00 a 18:00',
                'contact_name' => 'Centro Cádiz Paquetes',
                'contact_phone' => '956112233',
                'contact_email' => 'cadiz@paq.com',
            ],
            [
                'address' => 'Calle Laurel 15',
                'zip' => '26001',
                'country' => 'Centro',
                'city' => 'Logroño',
                'role_address' => '1',
                'notes' => 'Horario de atención: Lunes a Viernes de 9:00 a 18:00',
                'contact_name' => 'Paq Logroño',
                'contact_phone' => '941223344',
                'contact_email' => 'logrono@paq.com',
            ],
            [
                'address' => 'Paseo del Espolón 3',
                'zip' => '09003',
                'country' => 'Centro',
                'city' => 'Burgos',
                'role_address' => '1',
                'notes' => 'Horario de atención: Lunes a Viernes de 9:00 a 18:00',
                'contact_name' => 'Centro Burgos Recojida',
                'contact_phone' => '947334455',
                'contact_email' => 'burgos@paq.com',
            ],
            [
                'address' => 'Rambla Obispo Orberá 8',
                'zip' => '04001',
                'country' => 'Centro',
                'city' => 'Almería',
                'role_address' => '1',
                'notes' => 'Horario de atención: Lunes a Viernes de 9:00 a 18:00',
                'contact_name' => 'Establecimiento Almería',
                'contact_phone' => '950778899',
                'contact_email' => 'almeria@paq.com',
            ],
            [
                'address' => 'Avenida Andalucía 55',
                'zip' => '21005',
                'country' => 'Isla Chica',
                'city' => 'Huelva',
                'role_address' => '1',
                'notes' => 'Horario de atención: Lunes a Viernes de 9:00 a 18:00',
                'contact_name' => 'Paq Huelva Norte',
                'contact_phone' => '959223344',
                'contact_email' => 'huelva@paq.com',
            ],
            [
                'address' => 'Zocodover 2',
                'zip' => '45001',
                'country' => 'Casco Histórico',
                'city' => 'Toledo',
                'role_address' => '1',
                'notes' => 'Horario de atención: Lunes a Viernes de 9:00 a 18:00',
                'contact_name' => 'Punto Toledo Express',
                'contact_phone' => '925112233',
                'contact_email' => 'toledo@paq.com',
            ],
            [
                'address' => 'Plaza Mayor 20',
                'zip' => '37002',
                'country' => 'Centro',
                'city' => 'Salamanca',
                'role_address' => '1',
                'notes' => 'Horario de atención: Lunes a Viernes de 9:00 a 18:00',
                'contact_name' => 'Estación de Paquetes Salamanca',
                'contact_phone' => '923334455',
                'contact_email' => 'salamanca@paq.com',
            ],
            [
                'address' => 'Paseo de la Estación 10',
                'zip' => '23008',
                'country' => 'Centro',
                'city' => 'Jaén',
                'role_address' => '1',
                'notes' => 'Horario de atención: Lunes a Viernes de 9:00 a 18:00',
                'contact_name' => 'Recojida Jaén Centro',
                'contact_phone' => '953223344',
                'contact_email' => 'jaen@paq.com',
            ],
            [
                'address' => 'Calle Burgos 25',
                'zip' => '39001',
                'country' => 'Centro',
                'city' => 'Santander',
                'role_address' => '1',
                'notes' => 'Horario de atención: Lunes a Viernes de 9:00 a 18:00',
                'contact_name' => 'Paq Santander Express',
                'contact_phone' => '942556677',
                'contact_email' => 'santander@paq.com',
            ],
            [
                'address' => 'Calle Carretería 50',
                'zip' => '16004',
                'country' => 'Centro',
                'city' => 'Cuenca',
                'role_address' => '1',
                'notes' => 'Horario de atención: Lunes a Viernes de 9:00 a 18:00',
                'contact_name' => 'Centro Cuenca Paquetes',
                'contact_phone' => '969778899',
                'contact_email' => 'cuenca@paq.com',
            ],
            [
                'address' => 'Plaza del Torico 3',
                'zip' => '44001',
                'country' => 'Centro',
                'city' => 'Teruel',
                'role_address' => '1',
                'notes' => 'Horario de atención: Lunes a Viernes de 9:00 a 18:00',
                'contact_name' => 'Punto Recojida Teruel',
                'contact_phone' => '978223344',
                'contact_email' => 'teruel@paq.com',
            ],
            [
                'address' => 'Calle Mayor 18',
                'zip' => '12001',
                'country' => 'Centro',
                'city' => 'Castellón',
                'role_address' => '1',
                'notes' => 'Horario de atención: Lunes a Viernes de 9:00 a 18:00',
                'contact_name' => 'Paq Castellón Central',
                'contact_phone' => '964112233',
                'contact_email' => 'castellon@paq.com',
            ],

        
        ];

        foreach ($ship_add as $address) {
            ShippingAddress::create($address);
        }
    }
}
